name: Flutter Web
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.7.12'
      - name: Enable Flutter Web
        run: flutter config --enable-web
      - name: Get Dependencies
        working-directory: ./seeds
        run: flutter pub get
      - name: Build Web Release
        working-directory: ./seeds
        run: flutter build web --release --base-href /scripture-seeds/ --web-renderer canvaskit
      - name: Push to GitHub Pages
        working-directory: ./seeds
        run: |
          cd build/web
          git init
          git config --global user.email nathanwalker1208@gmail.com
          git config --global user.name "Nathan Walker"
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/NWalker1208/scripture-seeds.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
